// User-defined event presets. A preset is a saved EventBinding template
// — an event trigger plus a sequence of pre-filled actions — that the
// user can stamp onto any element with one click instead of building the
// same chain by hand each time.
//
// Storage: localStorage under `lc-event-presets`, JSON array. The shape
// mirrors EventBinding minus the autogenerated id; applying a preset
// mints fresh ids so each instance is independent.

import type { Action, EventBinding } from "./types";
import { makeId } from "./id";

const STORAGE_KEY = "lc-event-presets";

export type EventPreset = {
  // Stable id for the preset row itself (used as the React key and as
  // the value emitted by the dropdown). Distinct from the EventBinding
  // id minted on apply.
  id: string;
  name: string;
  event: string;
  actions: Action[];
};

export function loadPresets(): EventPreset[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function savePresets(presets: EventPreset[]): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(presets));
  } catch {
    // localStorage may be unavailable (private mode quota etc.) — drop silently.
  }
}

// Build a fresh EventBinding from a preset, minting a new binding id and
// fresh ids for every action (including those nested inside ifElse and
// setTimeout). Without the deep walk, two stamped instances would share
// action ids and step on each other.
export function applyPreset(preset: EventPreset): EventBinding {
  return {
    id: makeId("evt"),
    event: preset.event,
    actions: preset.actions.map(reIdAction),
  };
}

function reIdAction(action: Action): Action {
  switch (action.kind) {
    case "ifElse":
      return {
        ...action,
        id: makeId("act"),
        then: action.then.map(reIdAction),
        else: action.else.map(reIdAction),
      };
    case "setTimeout":
      return {
        ...action,
        id: makeId("act"),
        actions: action.actions.map(reIdAction),
      };
    default:
      return { ...action, id: makeId("act") };
  }
}

// Build a preset from an existing binding (used by the "save as preset"
// button on a configured binding). The binding's own id is dropped; the
// preset gets its own id. Action ids are kept — they'll be replaced by
// `applyPreset` when the preset is stamped onto an element.
export function presetFromBinding(
  binding: EventBinding,
  name: string
): EventPreset {
  return {
    id: makeId("preset"),
    name,
    event: binding.event,
    actions: binding.actions,
  };
}
