// User-defined event presets. A preset is a saved EventBinding template
// — an event trigger plus a sequence of pre-filled actions — that the
// user can stamp onto any element with one click instead of building the
// same chain by hand each time.
//
// Storage: backend at /api/lc-presets/ (single global blob shared across
// every editor user and every saved page) plus a localStorage cache for
// offline fallback. The hook below orchestrates the two — see usePresets.
// The shape mirrors EventBinding minus the autogenerated id; applying a
// preset mints fresh ids so each instance is independent.

import { useCallback, useEffect, useRef, useState } from "react";

import type { Action, EventBinding } from "./types";
import { makeId } from "./id";

const STORAGE_KEY = "lc-event-presets";
const CHANGE_EVENT = "lc-event-presets-changed";
const PUSH_DEBOUNCE_MS = 250;

export type EventPreset = {
  // Stable id for the preset row itself (used as the React key and as
  // the value emitted by the dropdown). Distinct from the EventBinding
  // id minted on apply.
  id: string;
  name: string;
  event: string;
  actions: Action[];
};

// ─── localStorage cache (sync) ────────────────────────────────────────

export function loadPresets(): EventPreset[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function savePresets(presets: EventPreset[]): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(presets));
    window.dispatchEvent(new CustomEvent(CHANGE_EVENT));
  } catch {
    // localStorage may be unavailable (private mode quota etc.) — drop silently.
  }
}

// ─── backend client (async) ───────────────────────────────────────────

function backendBaseUrl(): string | null {
  const url = process.env.NEXT_PUBLIC_LC_BACKEND_URL;
  if (!url) return null;
  return url.replace(/\/$/, "");
}

export async function fetchPresetsFromBackend(): Promise<EventPreset[]> {
  const base = backendBaseUrl();
  if (!base) throw new Error("NEXT_PUBLIC_LC_BACKEND_URL is not set");
  const res = await fetch(`${base}/api/lc-presets/`, { cache: "no-store" });
  if (!res.ok) {
    throw new Error(`Backend returned ${res.status}: ${res.statusText}`);
  }
  const data = (await res.json()) as { presets?: EventPreset[] };
  return Array.isArray(data.presets) ? data.presets : [];
}

export async function pushPresetsToBackend(
  presets: EventPreset[]
): Promise<void> {
  const base = backendBaseUrl();
  if (!base) throw new Error("NEXT_PUBLIC_LC_BACKEND_URL is not set");
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  const token = process.env.NEXT_PUBLIC_LC_BACKEND_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;
  const res = await fetch(`${base}/api/lc-presets/`, {
    method: "PUT",
    headers,
    body: JSON.stringify({ presets }),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(
      `Backend returned ${res.status}: ${detail || res.statusText}`
    );
  }
}

// ─── React hook ───────────────────────────────────────────────────────

export type PresetsSyncStatus =
  | { kind: "loading" }
  | { kind: "synced" }
  | { kind: "saving" }
  | { kind: "error"; message: string };

export type UsePresetsReturn = {
  presets: EventPreset[];
  status: PresetsSyncStatus;
  // Replace the whole list. Updates the local cache and React state
  // immediately, then writes through to the backend (debounced so rapid
  // edits don't hammer the server). Errors surface on `status`.
  setPresets: (next: EventPreset[]) => void;
};

// One-shot orchestration of cache + backend.
//
// Lifecycle:
//   1. mount → seed state from localStorage cache (instant render),
//      kick off a backend fetch, replace state if backend has more recent
//      data.
//   2. one-time migration: if the backend is empty (first deploy of this
//      feature) but the cache has presets, push the cache up so existing
//      users don't lose their work.
//   3. setPresets → optimistic local update + debounced PUT to backend.
//   4. cross-component sync: dispatches a CustomEvent on cache writes so
//      other usePresets() instances refresh from the cache without
//      racing each other to the backend.
export function usePresets(): UsePresetsReturn {
  const [presets, setLocal] = useState<EventPreset[]>(() => loadPresets());
  const [status, setStatus] = useState<PresetsSyncStatus>({ kind: "loading" });
  const pushTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const lastPushed = useRef<string>(JSON.stringify(presets));

  // Initial fetch + migration.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const remote = await fetchPresetsFromBackend();
        if (cancelled) return;
        const cached = loadPresets();
        // First-deploy migration: empty server + non-empty cache → seed
        // backend with whatever the user already had locally.
        if (remote.length === 0 && cached.length > 0) {
          try {
            await pushPresetsToBackend(cached);
            lastPushed.current = JSON.stringify(cached);
            setStatus({ kind: "synced" });
            return; // keep current local state
          } catch (err) {
            // Migration push failed (no token, network) — fall through and
            // keep cache visible; status reflects the failure.
            setStatus({
              kind: "error",
              message:
                "Couldn't push cached presets to backend: " +
                (err instanceof Error ? err.message : String(err)),
            });
            return;
          }
        }
        // Normal path: backend wins. Mirror to cache so the next mount
        // can render synchronously without a flash.
        savePresets(remote);
        setLocal(remote);
        lastPushed.current = JSON.stringify(remote);
        setStatus({ kind: "synced" });
      } catch (err) {
        if (cancelled) return;
        setStatus({
          kind: "error",
          message:
            "Couldn't fetch presets from backend: " +
            (err instanceof Error ? err.message : String(err)),
        });
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  // Cross-component sync: another usePresets() instance saved → mirror.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const refresh = () => setLocal(loadPresets());
    window.addEventListener(CHANGE_EVENT, refresh);
    window.addEventListener("storage", refresh);
    return () => {
      window.removeEventListener(CHANGE_EVENT, refresh);
      window.removeEventListener("storage", refresh);
    };
  }, []);

  const setPresets = useCallback((next: EventPreset[]) => {
    // Optimistic local update — mirrors to cache + dispatches CHANGE_EVENT
    // so peer components re-read.
    savePresets(next);
    setLocal(next);

    // Debounce the network push: dragging an action's slider would
    // otherwise issue dozens of PUTs per second.
    if (pushTimer.current) clearTimeout(pushTimer.current);
    setStatus({ kind: "saving" });
    pushTimer.current = setTimeout(async () => {
      const serialized = JSON.stringify(next);
      // Skip the push if nothing actually changed since the last push —
      // happens on cross-component sync after a peer already wrote.
      if (serialized === lastPushed.current) {
        setStatus({ kind: "synced" });
        return;
      }
      try {
        await pushPresetsToBackend(next);
        lastPushed.current = serialized;
        setStatus({ kind: "synced" });
      } catch (err) {
        setStatus({
          kind: "error",
          message:
            "Couldn't save presets: " +
            (err instanceof Error ? err.message : String(err)),
        });
      }
    }, PUSH_DEBOUNCE_MS);
  }, []);

  return { presets, status, setPresets };
}

// Build a fresh EventBinding from a preset, minting a new binding id and
// fresh ids for every action (including those nested inside ifElse and
// setTimeout). Without the deep walk, two stamped instances would share
// action ids and step on each other.
export function applyPreset(preset: EventPreset): EventBinding {
  return {
    id: makeId("evt"),
    event: preset.event,
    actions: preset.actions.map(reIdAction),
  };
}

function reIdAction(action: Action): Action {
  switch (action.kind) {
    case "ifElse":
      return {
        ...action,
        id: makeId("act"),
        then: action.then.map(reIdAction),
        else: action.else.map(reIdAction),
      };
    case "setTimeout":
      return {
        ...action,
        id: makeId("act"),
        actions: action.actions.map(reIdAction),
      };
    default:
      return { ...action, id: makeId("act") };
  }
}

// Build a preset from an existing binding (used by the "save as preset"
// button on a configured binding). The binding's own id is dropped; the
// preset gets its own id. Action ids are kept — they'll be replaced by
// `applyPreset` when the preset is stamped onto an element.
export function presetFromBinding(
  binding: EventBinding,
  name: string
): EventPreset {
  return {
    id: makeId("preset"),
    name,
    event: binding.event,
    actions: binding.actions,
  };
}
